### ISSUE TITLE
Wrong links inserted

### ISSUE THREAD

**Issue by JoPark20** [X9Developers/stakenet-web-ui#18]
**Bug Description**
Clicking on some headers lead to the wrong pages

**Steps to Reproduce**
1. Click on "About / Docs / Code / Analytics / BTC / Charts"

**Expected Behavior**
It should lead to Stakenet pages / docs.

**Additional Context**
![Screenshot (434)_LI](https://user-images.githubusercontent.com/43677783/126668875-9b65b09a-60a6-4c68-a9f5-3a84551a475d.jpg)

![Screenshot (439)_LI](https://user-images.githubusercontent.com/43677783/126673834-97a41bc2-bc26-410c-97b7-225276aa7938.jpg)

**Comment by JoPark20** [comment]
Feature request: Once the Stakenet DEX is published, the BTC link should lead to this DEX.

**Comment by iBlackShadow** [comment]
these sections were hidden for now
