### ISSUE TITLE
Wallet: small typo at the bottom

### ISSUE THREAD

**Issue by JoPark20** [X9Developers/stakenet-web-ui#23]
**Bug Description**
On the page to recover a stakenet wallet, there is a typo at the bottom "coditions" instead of "conditions". I 

**Steps to Reproduce**
1. Go to Wallet

**Expected Behavior**
More correct would be: "I agree to the Terms and Conditions"

**Additional Context**
![Capture_decran_2021-07-22_a_19.05.40.png](https://user-images.githubusercontent.com/43677783/126681886-4b81591b-21f7-4c4b-8a5b-bdb59f14fe7d.png)

**Comment by Stakelord54** [comment]
Also a small typo in creation of wallet menu:
![image](https://user-images.githubusercontent.com/87782707/126805360-591ebc59-9387-4ec8-a9e3-f65c4d163cda.png)

**Comment by iBlackShadow** [comment]
fixed in #31
